import type { Recipe } from "./types";

/** 1. aşamada arayüzü doldurmak için örnek veri. 3. aşamada Supabase'e bağlanınca kaldırılır. */
export const SAMPLE_RECIPES: Recipe[] = [
  {
    id: "s1",
    user_id: "demo",
    title: "Mercimek Çorbası",
    status: "made",
    category: "Çorbalar",
    subcategory: "Bakliyat çorbaları",
    servings: 4,
    original_servings: 4,
    time_text: "35 dk",
    ingredients: [
      { id: "a", name: "kırmızı mercimek", amount: 1, unit: "su bardağı" },
      { id: "b", name: "soğan", amount: 1, unit: "adet" },
      { id: "c", name: "un", amount: 1, unit: "yemek kaşığı" },
      { id: "d", name: "tereyağı", amount: 2, unit: "yemek kaşığı" },
      { id: "e", name: "su", amount: 6, unit: "su bardağı" },
    ],
    steps: ["Soğanı kavur.", "Mercimek ve suyu ekle, 25 dakika pişir.", "Blenderdan geçir, tereyağıyla servis et."],
    notes: null,
    cover_path: null,
    source_url: "https://www.youtube.com/watch?v=example",
    source_platform: "youtube",
    source_author: "Örnek Kanal",
    source_author_url: null,
    confidence: { title: 0.98, servings: 0.9 },
    needs_review: false,
    made_at: "2026-09-20T18:00:00Z",
    created_at: "2026-09-18T10:00:00Z",
    updated_at: "2026-09-20T18:00:00Z",
  },
  {
    id: "s2",
    user_id: "demo",
    title: "Fırında Tavuk But",
    status: "todo",
    category: "Ana Yemekler",
    subcategory: "Tavuk yemekleri",
    servings: 4,
    original_servings: 4,
    time_text: "1 saat 10 dk",
    ingredients: [
      { id: "a", name: "tavuk but", amount: 1, unit: "kg" },
      { id: "b", name: "patates", amount: 4, unit: "adet" },
      { id: "c", name: "zeytinyağı", amount: 3, unit: "yemek kaşığı", estimated: true },
    ],
    steps: ["Baharatla marine et.", "200 derece fırında 50 dakika pişir."],
    notes: null,
    cover_path: null,
    source_url: "https://www.instagram.com/reel/example",
    source_platform: "instagram",
    source_author: "@ornekhesap",
    source_author_url: null,
    confidence: { title: 0.95, servings: 0.5 },
    needs_review: true,
    made_at: null,
    created_at: "2026-09-28T10:00:00Z",
    updated_at: "2026-09-28T10:00:00Z",
  },
  {
    id: "s3",
    user_id: "demo",
    title: "Islak Kek",
    status: "todo",
    category: "Tatlılar",
    subcategory: "Kekler & kurabiyeler",
    servings: 8,
    original_servings: 8,
    time_text: "50 dk",
    ingredients: [
      { id: "a", name: "un", amount: 2, unit: "su bardağı" },
      { id: "b", name: "toz şeker", amount: 1, unit: "su bardağı" },
      { id: "c", name: "yumurta", amount: 3, unit: "adet" },
      { id: "d", name: "kakao", amount: 3, unit: "yemek kaşığı" },
    ],
    steps: ["Yumurta ve şekeri çırp.", "Kuru malzemeleri ekle.", "180 derecede 35 dakika pişir."],
    notes: null,
    cover_path: null,
    source_url: "https://www.tiktok.com/@ornek/video/1",
    source_platform: "tiktok",
    source_author: "@ornek",
    source_author_url: null,
    confidence: { title: 0.97 },
    needs_review: true,
    made_at: null,
    created_at: "2026-09-29T10:00:00Z",
    updated_at: "2026-09-29T10:00:00Z",
  },
];
